# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
 standalone_tags:
   [
     {id: 1, size: .025, name: BASE},
     {id: 2, size: .025, name: LL},
     {id: 3, size: .025, name: TL},
     {id: 4, size: .025, name: LR},
     {id: 6, size: .025, name: UL},
     {id: 8, size: .025, name: UR}
   ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
 tag_bundles:
   [
     {
       name: 'CUSTOM_BUNDLE_NAME',
       layout:
         [
           {id: 1, size: 0.025, x: -0.25, y: -0.025, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
           {id: 2, size: 0.025, x: 0.25, y: -0.025, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
           {id: 3, size: 0.025, x: 0.25, y: 0.275, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}, 
           {id: 4, size: 0.025, x: -0.25, y: 0.275, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
         ]
     },
    #  {
    #    name: 'CUSTOM_BUNDLE_NAME_2',
    #    layout:
    #      [
    #        {id: 1, size: 0.025, x: -0.25, y: -0.025, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 2, size: 0.025, x: 0.25, y: -0.025, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 3, size: 0.025, x: 0.25, y: 0.275, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}, 
    #        {id: 4, size: 0.025, x: -0.25, y: 0.275, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 6, size: 0.025, x: -0.175, y: 0.350, z: 0.272, qw: 1, qx: 0, qy: 0, qz: 0}, 
    #        {id: 8, size: 0.025, x: 0.275, y: 0.050, z: 0.151, qw: 1, qx: 0, qy: 0, qz: 0}
    #      ]
    #  }
     {
       name: 'CUSTOM_BUNDLE_NAME_2',
       layout:
         [
           {id: 1, size: 0.025, x: -0.25, y: -0.025, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
           {id: 2, size: 0.025, x: 0.25, y: -0.025, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
           {id: 3, size: 0.025, x: 0.25, y: 0.275, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}, 
           {id: 4, size: 0.025, x: -0.25, y: 0.275, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
           {id: 6, size: 0.025, x: -0.375, y: 0.100, z: 0.272, qw: 1, qx: 0, qy: 0, qz: 0}, 
           {id: 7, size: 0.025, x: -0.225, y: 0.400, z: 0.151, qw: 1, qx: 0, qy: 0, qz: 0}, 
           {id: 8, size: 0.025, x: 0.325, y: 0.100, z: 0.151, qw: 1, qx: 0, qy: 0, qz: 0}
         ]
     }
   ]
